(**************************************************************************)
(*                                                                        *)
(*                         The Zen/Aum Library                            *)
(*                                                                        *)
(*                              Gérard Huet                               *)
(*                                                                        *)
(* ©2005 Institut National de Recherche en Informatique et en Automatique *)
(**************************************************************************)

(* Mechanically generated by [print_automaton] from source example.aut    *)
(* using the [Regular] module of Benoit Razet with the Camlp4 library     *)

